name: test
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        emacs_version:
        - 26.3
        - 27.1
        - 27.2
        - snapshot

    steps:
    - uses: actions/checkout@v2

    - name: Install emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Install Python
      uses: actions/setup-python@v2
      with:
          python-version: "3.6"
          architecture: "x64"

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          components: rust-analysis, rust-src, rls

    - name: Install eclipse.jdt.ls
      run: |
        curl -fSL https://download.eclipse.org/jdtls/snapshots/jdt-language-server-latest.tar.gz -o eclipse.tar.gz
        mkdir eclipse.jdt.ls
        tar -C eclipse.jdt.ls -xzf eclipse.tar.gz

    - name: Install other depedencies
      run: |
           pip3 install python-language-server autopep8 rope pycodestyle pyflakes pydocstyle mccabe pylint
           sudo apt-get install clangd-9

    - name: Build eglot
      run: make compile

    - name: Test eglot
      run: |
        export CLASSPATH=$(pwd)/$(find eclipse.jdt.ls/ -regex eclipse.jdt.ls/plugins/org.eclipse.equinox.launcher_.*.jar):${CLASSPATH}
        make eglot-check
